# Golang CircleCI 2.0 config file
version: 2
jobs:
  verify:
    docker:
    - image: circleci/golang:1.9
    working_directory: /go/src/github.com/peterstirrup/fifa
    steps:
    - checkout
    - run: go get -u golang.org/x/lint/golint
    - run: golint $(go list ./... | grep -v /vendor/)
    - run: go vet $(go list ./... | grep -v /vendor/)

  test:
    docker:
    - image: circleci/golang:1.9
    working_directory: /go/src/github.com/peterstirrup/fifa
    steps:
    - checkout
    - run: go test -v ./...

# define order of job execution
workflows:
  version: 2
  build_and_test:
    jobs:
    - verify:
    - test:
        requires:
        - verify